language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        # - python: 3.7
        #   env: TOXENV=py37
        #   Travis has problems with 3.7
install:
    - pip install -r requirements/base.txt
    - pip install tox==3.0.0
    - pip install coveralls==1.3.0
    - pip install coverage==4.5.1
before_script:
    - coverage erase
script:
    - coverage run --source=sexpr -m unittest tests; tox
after_success:
    - COVERALLS_REPO_TOKEN=TjK5cE7tSmwdo22vlNFAzSotc9o8trRJN coveralls
